apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo
spec: 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Recycle
  nfs:
    pat: /srv/demo
    server: mster.example.com